//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Struvio.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageTexts() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Struvio.Common.Localization.LanguageTexts", typeof(LanguageTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} alanı boş bırakılamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FieldIsEmpty {
            get {
                return ResourceManager.GetString("FieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kimlik bilgileri bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IdentityUserNotFound {
            get {
                return ResourceManager.GetString("IdentityUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola yeterince karmaşık değil. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola en az 8 en fazla 15 karakter olmalıdır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMustBeBetween8And15 {
            get {
                return ResourceManager.GetString("PasswordMustBeBetween8And15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola küçük harf içermelidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMustContainLowercase {
            get {
                return ResourceManager.GetString("PasswordMustContainLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola rakam içermelidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMustContainNumber {
            get {
                return ResourceManager.GetString("PasswordMustContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola özel karakter içermelidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMustContainSpecialCharacters {
            get {
                return ResourceManager.GetString("PasswordMustContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola büyük harf içermelidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMustContainUppercase {
            get {
                return ResourceManager.GetString("PasswordMustContainUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parolalar aynı değil. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
