//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Struvio.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageTexts() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Struvio.Common.Localization.LanguageTexts", typeof(LanguageTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Aksiyon adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tümü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API anahtarı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API parolası benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ApiPassword {
            get {
                return ResourceManager.GetString("ApiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onay benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onaylı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kod (Dile özgü) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CodeLanguageSpecific {
            get {
                return ResourceManager.GetString("CodeLanguageSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kontrolör adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluşturulma tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oluşturan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Açıklama benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bitiş tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} alanı boş bırakılamaz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string FieldIsEmpty {
            get {
                return ResourceManager.GetString("FieldIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kimlik no benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IdentityNumber {
            get {
                return ResourceManager.GetString("IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kimlik bilgileri bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string IdentityUserNotFound {
            get {
                return ResourceManager.GetString("IdentityUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta adresi geçerli değil. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola yeterince karmaşık değil. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Değiştirilme tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LastModificationTime {
            get {
                return ResourceManager.GetString("LastModificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Değiştiren benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string LastModifier {
            get {
                return ResourceManager.GetString("LastModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Onaysız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Organizasyon benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola en az 8 en fazla 15 karakter olmalıdır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMustBeBetween8And15 {
            get {
                return ResourceManager.GetString("PasswordMustBeBetween8And15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola küçük harf içermelidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMustContainLowercase {
            get {
                return ResourceManager.GetString("PasswordMustContainLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola rakam içermelidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMustContainNumber {
            get {
                return ResourceManager.GetString("PasswordMustContainNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola özel karakter içermelidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMustContainSpecialCharacters {
            get {
                return ResourceManager.GetString("PasswordMustContainSpecialCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola büyük harf içermelidir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordMustContainUppercase {
            get {
                return ResourceManager.GetString("PasswordMustContainUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parolalar aynı değil. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon no benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt bulunamadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Aranan benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Searched {
            get {
                return ResourceManager.GetString("Searched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sıra no benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string SequenceNumber {
            get {
                return ResourceManager.GetString("SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlangıç tarihi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlama zamanı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Durum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kullanıcı adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sürüm benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
